export const salesData = [
  // QUINTILIANO - COSTEÑA
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES ABAD RIVERA",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES FLORES MAGON",
    quota: 133,
    progress: 0,
    difference: -133,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES GALEANA",
    quota: 186,
    progress: 0,
    difference: -186,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES GUALUPITA",
    quota: 475,
    progress: 0,
    difference: -475,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES JOJUTLA CENTRO",
    quota: 305,
    progress: 0,
    difference: -305,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES MOYOTEPEC",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  { seller: "QUINTILIANO", brand: "COSTEÑA", store: "ABARROTERA FUENTES NAVE D", quota: 0, progress: 0, difference: 0 },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES OAXTEPEC",
    quota: 33,
    progress: 0,
    difference: -33,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES PALMAS",
    quota: 433,
    progress: 0,
    difference: -433,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES PLAZA SOL",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES PTE IXTLA CENTRO",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES PTE IXTLA MERCADO",
    quota: 127,
    progress: 0,
    difference: -127,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES YAUTEPEC",
    quota: 456,
    progress: 0,
    difference: -456,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES ZACARIAS",
    quota: 157,
    progress: 0,
    difference: -157,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ABARROTES CASA REZA SA DE CV",
    quota: 455,
    progress: 0,
    difference: -455,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ALEJANDRO MOJICA REYES",
    quota: 526,
    progress: 0,
    difference: -526,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ALFONZINA BENITEZ VILLALOBOS",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "ALTAGRACIA MAXELLI BORJA RODRIGUEZ",
    quota: 192,
    progress: 0,
    difference: -192,
  },
  {
    seller: "QUINTILIANO",
    brand: "COSTEÑA",
    store: "AMALIA GONZALEZ GUZMAN",
    quota: 353,
    progress: 0,
    difference: -353,
  },

  // QUINTILIANO - JUMEX
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES ABAD RIVERA",
    quota: 416,
    progress: 0,
    difference: -416,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES FLORES MAGON",
    quota: 51,
    progress: 0,
    difference: -51,
  },
  { seller: "QUINTILIANO", brand: "JUMEX", store: "ABARROTERA FUENTES GALEANA", quota: 0, progress: 0, difference: 0 },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES GUALUPITA",
    quota: 219,
    progress: 0,
    difference: -219,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES JOJUTLA CENTRO",
    quota: 226,
    progress: 0,
    difference: -226,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES MOYOTEPEC",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES NAVE D",
    quota: 334,
    progress: 0,
    difference: -334,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES OAXTEPEC",
    quota: 128,
    progress: 0,
    difference: -128,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES PALMAS",
    quota: 347,
    progress: 0,
    difference: -347,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES PLAZA SOL",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES PTE IXTLA CENTRO",
    quota: 289,
    progress: 0,
    difference: -289,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES PTE IXTLA MERCADO",
    quota: 117,
    progress: 0,
    difference: -117,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES YAUTEPEC",
    quota: 225,
    progress: 0,
    difference: -225,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES ZACARIAS",
    quota: 433,
    progress: 0,
    difference: -433,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ABARROTES CASA REZA SA DE CV",
    quota: 347,
    progress: 0,
    difference: -347,
  },
  { seller: "QUINTILIANO", brand: "JUMEX", store: "ALEJANDRO MOJICA REYES", quota: 0, progress: 0, difference: 0 },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ALFONZINA BENITEZ VILLALOBOS",
    quota: 0,
    progress: 0,
    difference: 0,
  },
  {
    seller: "QUINTILIANO",
    brand: "JUMEX",
    store: "ALTAGRACIA MAXELLI BORJA RODRIGUEZ",
    quota: 108,
    progress: 0,
    difference: -108,
  },
  { seller: "QUINTILIANO", brand: "JUMEX", store: "AMALIA GONZALEZ GUZMAN", quota: 137, progress: 0, difference: -137 },

  // LAYDA - TOTIS
  { seller: "LAYDA", brand: "TOTIS", store: "NANCY CARIME MORALES CANDANEDO", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "ADELAIDA IRAZOQUE CAMPOS", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "ARACELI LOPEZ RIVERA", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "FERNANDO LOPEZ RIVERA", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "EFREN LEGUIZANO LUGO", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "GABRIEL TORRES ESCOBAR", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "ABASTECEDORA DE DULCES YAMI", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "JORGE TRUJILLO VALENZO", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "JOSE LUIS GARRIDO BELTRAN", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "JOSE ARTURO BARRERA ALVAREZ", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "NOE ARROYO CONCHA", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "DULCERIA EL TAPONCITO", quota: 0, progress: 0, difference: 0 },
  { seller: "LAYDA", brand: "TOTIS", store: "KARLA VIANEY ORTEGA MARTINEZ", quota: 0, progress: 0, difference: 0 },

  // Datos de ejemplo para otro vendedor
  {
    seller: "CARLOS",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES ABAD RIVERA",
    quota: 320,
    progress: 120,
    difference: -200,
  },
  {
    seller: "CARLOS",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES FLORES MAGON",
    quota: 150,
    progress: 50,
    difference: -100,
  },
  {
    seller: "CARLOS",
    brand: "COSTEÑA",
    store: "ABARROTERA FUENTES GALEANA",
    quota: 200,
    progress: 75,
    difference: -125,
  },
  {
    seller: "CARLOS",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES ABAD RIVERA",
    quota: 380,
    progress: 180,
    difference: -200,
  },
  {
    seller: "CARLOS",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES FLORES MAGON",
    quota: 120,
    progress: 40,
    difference: -80,
  },
  {
    seller: "CARLOS",
    brand: "JUMEX",
    store: "ABARROTERA FUENTES GALEANA",
    quota: 250,
    progress: 100,
    difference: -150,
  },
]
